# Generated by Django 3.2.8 on 2022-02-23 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_rename_post_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='duties',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='qualification',
            field=models.TextField(null=True),
        ),
    ]
